name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.13.0-chrome-124.0.6367.155-1-ff-125.0.3-edge-124.0.2478.80-1
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 9.1.1
      - uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        id: cypress
        with:
          build: pnpm build
          start: pnpm start
          browser: chrome
